version: 2

models:

  - name: stg_customers
    description: "Cleaned customer master data"
    columns:
      - name: customer_id
        description: "Primary customer identifier"
        tests:
          - not_null

      - name: customer_unique_id
        description: "Stable identifier across multiple orders"
        tests:
          - not_null

      - name: customer_state
        description: "Brazilian state code"
        tests:
          - not_null
          - accepted_values:
              values:
                - AC
                - AL
                - AP
                - AM
                - BA
                - CE
                - DF
                - ES
                - GO
                - MA
                - MT
                - MS
                - MG
                - PA
                - PB
                - PR
                - PE
                - PI
                - RJ
                - RN
                - RS
                - RO
                - RR
                - SC
                - SP
                - SE
                - TO

  - name: stg_geolocation
    description: "ZIP-level geolocation reference data"
    columns:
      - name: zip_code_prefix
        tests:
          - not_null

      - name: latitude
        tests:
          - not_null

      - name: longitude
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned orders data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

      - name: order_status
        tests:
          - not_null
          - accepted_values:
              values:
                - created
                - approved
                - invoiced
                - processing
                - shipped
                - delivered
                - canceled
                - unavailable

      - name: order_purchase_timestamp
        tests:
          - not_null

  - name: stg_order_items
    description: "Order line items"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - order_item_id

    columns:
      - name: order_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

      - name: seller_id
        tests:
          - not_null

      - name: price
        tests:
          - not_null

  - name: stg_order_payments
    description: "Payment details per order"
    columns:
      - name: order_id
        tests:
          - not_null

      - name: payment_type
        tests:
          - not_null
          - accepted_values:
              values:
                - credit_card
                - boleto
                - voucher
                - debit_card
                - not_defined

      - name: payment_value
        tests:
          - not_null

  - name: stg_order_reviews
    description: "Latest review per order"
    columns:
      - name: review_id
        tests:
          - not_null

      - name: order_id
        tests:
          - not_null
          - unique

      - name: review_score
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]

  - name: stg_products
    description: "Cleaned product catalog"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

      - name: product_weight_g
        description: "Product weight in grams; may be null for incomplete listings"


  - name: stg_product_category_translation
    description: "Product category translation mapping"
    columns:
      - name: product_category_name
        tests:
          - not_null
          - unique

      - name: product_category_name_english
        tests:
          - not_null

  - name: stg_sellers
    description: "Seller master data"
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique

      - name: seller_state
        tests:
          - not_null
